import { useEffect, useState } from 'react';
import { Activity, CalendarDays, CircleDollarSign, Headphones, Users } from 'lucide-react';
import './styles.css';

type Summary = { revenueThisMonth: number; bookingsToday: number; activeLeads: number; activeProjects: number; outstandingInvoices: number };
type Business = { tradingName: string; slogan: string; city: string; province: string };

export function App() {
  const [business, setBusiness] = useState<Business | null>(null);
  const [summary, setSummary] = useState<Summary | null>(null);
  useEffect(() => { fetch('/api/v1/business').then((r) => r.ok ? r.json() : null).then(setBusiness); fetch('/api/v1/dashboard/summary', { credentials: 'include' }).then((r) => r.ok ? r.json() : null).then(setSummary); }, []);
  const money = (value: number) => new Intl.NumberFormat('en-ZA', { style: 'currency', currency: 'ZAR' }).format(value);
  return <main className="shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">BS</div><div><strong>Blue Sine</strong><span>Music Studios</span></div></div><nav><a className="active">Dashboard</a><a href="#crm">CRM</a><a href="#bookings">Bookings</a><a href="#projects">Projects</a><a href="#finance">Finance</a><a href="#agents">AI Agents</a><a href="#reports">Reports</a><a href="#settings">Settings</a></nav></aside><section className="content"><header className="topbar"><div><p className="eyebrow">OWNER COMMAND CENTRE</p><h1>Good morning{business ? `, ${business.tradingName}` : ''}</h1><p className="muted">Creating sound. Building stars.</p></div><button className="primary" onClick={() => window.alert('AI command centre will be enabled in the next agent phase.')}>Ask Blue Sine AI</button></header><section className="brief"><div><p className="eyebrow">AI CEO DAILY BRIEFING</p><h2>Your studio at a glance</h2><p className="muted">Live Phase 2 metrics are loaded from the connected API when authenticated.</p></div><Activity size={32} /></section><div className="metrics"><Metric icon={<CircleDollarSign />} label="Revenue this month" value={summary ? money(summary.revenueThisMonth) : '—'} /><Metric icon={<CalendarDays />} label="Bookings today" value={summary ? String(summary.bookingsToday) : '—'} /><Metric icon={<Users />} label="Active leads" value={summary ? String(summary.activeLeads) : '—'} /><Metric icon={<Headphones />} label="Active projects" value={summary ? String(summary.activeProjects) : '—'} /></div><div className="grid"><article className="card"><h3>Today’s studio</h3><p className="muted">{summary ? `${summary.bookingsToday} booking(s) scheduled today.` : 'Sign in to view live bookings.'}</p></article><article className="card"><h3>Finance</h3><p className="muted">{summary ? `${money(summary.outstandingInvoices)} outstanding.` : 'Sign in to view finance metrics.'}</p></article></div></section></main>;
}
function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <article className="metric"><div className="metric-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong></div></article>; }
