import { randomBytes } from 'node:crypto';
import type { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';
import type pg from 'pg';
import { hashPassword, hashToken, requireAuth, verifyPassword } from './auth.js';

type Ctx = FastifyRequest & { user?: { id: string; tenantId: string; email: string; role: string } };
const authUser = (request: Ctx) => request.user!;
const tenantId = (request: Ctx) => authUser(request).tenantId;
const money = (value: unknown) => { const n = Number(value); if (!Number.isFinite(n) || n < 0) throw new Error('Invalid monetary value'); return Math.round(n * 100) / 100; };

export function registerPhase2Routes(app: FastifyInstance, pool: pg.Pool) {
  app.get('/api/v1/business', async (_request, reply) => {
    const result = await pool.query('SELECT b.trading_name AS "tradingName", b.legal_name AS "legalName", b.business_type AS "businessType", b.city, b.province, b.country_code AS "countryCode", b.website, s.currency, s.timezone, s.business_hours AS "businessHours" FROM businesses b JOIN business_settings s ON s.business_id=b.id ORDER BY b.created_at LIMIT 1');
    if (!result.rows[0]) return reply.code(404).send({ error: 'Business not configured' });
    return { ...result.rows[0], slogan: 'Creating sound. Building stars.' };
  });

  app.post('/api/v1/auth/login', async (request, reply) => {
    const body = request.body as { email?: string; password?: string };
    if (!body.email || !body.password) return reply.code(400).send({ error: 'Email and password are required' });
    const found = await pool.query('SELECT id, tenant_id AS "tenantId", email, role, password_hash FROM app_users WHERE lower(email)=lower($1) AND active=true LIMIT 1', [body.email]);
    const record = found.rows[0];
    if (!record || !verifyPassword(body.password, record.password_hash)) return reply.code(401).send({ error: 'Invalid credentials' });
    const raw = randomBytes(32).toString('hex');
    await pool.query("INSERT INTO sessions (tenant_id,user_id,token_hash,expires_at) VALUES ($1,$2,$3,now()+interval '7 days')", [record.tenantId, record.id, hashToken(raw)]);
    reply.setCookie('session', raw, { httpOnly: true, sameSite: 'lax', secure: process.env.NODE_ENV === 'production', path: '/', maxAge: 60 * 60 * 24 * 7 });
    return { user: { id: record.id, tenantId: record.tenantId, email: record.email, role: record.role } };
  });
  app.post('/api/v1/auth/logout', async (request, reply) => { const token = request.cookies.session; if (token) await pool.query('DELETE FROM sessions WHERE token_hash=$1', [hashToken(token)]); reply.clearCookie('session', { path: '/' }); return { ok: true }; });
  app.get('/api/v1/auth/me', { preHandler: requireAuth }, async (request: Ctx) => ({ user: authUser(request) }));

  app.get('/api/v1/services', { preHandler: requireAuth }, async (request: Ctx) => pool.query('SELECT s.id,s.name,s.category,s.duration_minutes AS "durationMinutes",p.amount,p.currency FROM services s JOIN LATERAL (SELECT amount,currency FROM service_prices WHERE service_id=s.id AND tenant_id=$1 AND active=true AND effective_from<=now() AND (effective_to IS NULL OR effective_to>now()) ORDER BY effective_from DESC LIMIT 1) p ON true WHERE s.tenant_id=$1 AND s.active=true ORDER BY s.name', [tenantId(request)]).then((r) => r.rows));
  app.get('/api/v1/leads', { preHandler: requireAuth }, async (request: Ctx) => pool.query('SELECT * FROM leads WHERE tenant_id=$1 AND do_not_contact=false ORDER BY created_at DESC', [tenantId(request)]).then((r) => r.rows));
  app.post('/api/v1/leads', { preHandler: requireAuth }, async (request: Ctx, reply) => { const b=request.body as any; if(!b.name) return reply.code(400).send({error:'Name is required'}); const r=await pool.query('INSERT INTO leads (tenant_id,name,email,phone_e164,whatsapp_e164,source,source_url,status,score) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[tenantId(request),b.name,b.email??null,b.phoneE164??null,b.whatsappE164??null,b.source??'manual',b.sourceUrl??null,b.status??'New',Math.max(0,Math.min(100,Number(b.score??0)))]); return reply.code(201).send(r.rows[0]); });
  app.get('/api/v1/customers', { preHandler: requireAuth }, async (request: Ctx) => pool.query('SELECT * FROM customers WHERE tenant_id=$1 AND deleted_at IS NULL ORDER BY created_at DESC',[tenantId(request)]).then(r=>r.rows));
  app.post('/api/v1/customers', { preHandler: requireAuth }, async (request: Ctx, reply) => { const b=request.body as any; if(!b.displayName) return reply.code(400).send({error:'Display name is required'}); const r=await pool.query('INSERT INTO customers (tenant_id,display_name,email,phone_e164,whatsapp_e164,marketing_opt_in) VALUES ($1,$2,$3,$4,$5,$6) RETURNING *',[tenantId(request),b.displayName,b.email??null,b.phoneE164??null,b.whatsappE164??null,Boolean(b.marketingOptIn)]); return reply.code(201).send(r.rows[0]); });

  app.get('/api/v1/availability', { preHandler: requireAuth }, async (request: Ctx) => { const q=request.query as any; return pool.query("SELECT s.id,s.name FROM studios s WHERE s.tenant_id=$1 AND s.active=true AND NOT EXISTS (SELECT 1 FROM bookings b WHERE b.studio_id=s.id AND b.status<>'Cancelled' AND tstzrange(b.starts_at,b.ends_at,'[)') && tstzrange($2::timestamptz,$3::timestamptz,'[)'))",[tenantId(request),q.startsAt,q.endsAt]).then(r=>r.rows); });
  app.post('/api/v1/bookings', { preHandler: requireAuth }, async (request: Ctx, reply) => { const b=request.body as any; const client=await pool.connect(); try { await client.query('BEGIN'); const t=tenantId(request); const valid=await client.query('SELECT 1 FROM customers c JOIN services s ON s.tenant_id=c.tenant_id WHERE c.id=$1 AND s.id=$2 AND c.tenant_id=$3 AND c.deleted_at IS NULL AND s.active=true',[b.customerId,b.serviceId,t]); if(!valid.rows[0]) return reply.code(400).send({error:'Customer or service not found'}); const r=await client.query("INSERT INTO bookings (tenant_id,customer_id,service_id,studio_id,starts_at,ends_at,status,payment_status) VALUES ($1,$2,$3,$4,$5,$6,'Pending','Unpaid') RETURNING *",[t,b.customerId,b.serviceId,b.studioId,b.startsAt,b.endsAt]); await client.query('INSERT INTO outbox_events (tenant_id,event_type,aggregate_type,aggregate_id,payload) VALUES ($1,$2,$3,$4,$5)',[t,'booking.created','booking',r.rows[0].id,JSON.stringify(r.rows[0])]); await client.query('INSERT INTO audit_logs (tenant_id,actor_type,actor_id,action,entity_type,entity_id,details) VALUES ($1,$2,$3,$4,$5,$6,$7)',[t,'user',authUser(request).id,'booking.created','booking',r.rows[0].id,JSON.stringify({})]); await client.query('COMMIT'); return reply.code(201).send(r.rows[0]); } catch(e:any){ await client.query('ROLLBACK'); if(e.code==='23P01') return reply.code(409).send({error:'Studio is already booked for this time'}); throw e; } finally{client.release();} });

  app.post('/api/v1/quotes', { preHandler: requireAuth }, async (request: Ctx, reply) => { const b=request.body as any; const items=Array.isArray(b.items)?b.items:[]; if(!b.customerId||!items.length) return reply.code(400).send({error:'Customer and items are required'}); const client=await pool.connect(); try{await client.query('BEGIN'); const t=tenantId(request); let gross=0; let discountTotal=0; const validated:any[]=[]; for(const item of items){const p=await client.query('SELECT s.id,s.name,p.amount FROM services s JOIN LATERAL (SELECT amount FROM service_prices WHERE service_id=s.id AND tenant_id=$1 AND active=true ORDER BY effective_from DESC LIMIT 1) p ON true WHERE s.id=$2 AND s.tenant_id=$1',[t,item.serviceId]); if(!p.rows[0]) throw Object.assign(new Error('Service not found'),{statusCode:400}); const quantity=Number(item.quantity??1); const discount=money(item.discountAmount??0); const unit=money(p.rows[0].amount); gross+=unit*quantity; discountTotal+=discount; validated.push({serviceId:item.serviceId,description:item.description??p.rows[0].name,quantity,unit,discount});} const subtotal=money(gross); const total=money(gross-discountTotal); const number=`Q-${Date.now()}`; const q=await client.query("INSERT INTO quotes (tenant_id,customer_id,quote_number,status,subtotal,discount_total,total,valid_until) VALUES ($1,$2,$3,'Draft',$4,$5,$6,current_date+14) RETURNING *",[t,b.customerId,number,subtotal,discountTotal,total]); for(const i of validated) await client.query('INSERT INTO quote_items (tenant_id,quote_id,service_id,description,quantity,unit_price,discount_amount) VALUES ($1,$2,$3,$4,$5,$6,$7)',[t,q.rows[0].id,i.serviceId,i.description,i.quantity,i.unit,i.discount]); await client.query('COMMIT'); return reply.code(201).send({...q.rows[0],items:validated});}catch(e:any){await client.query('ROLLBACK');return reply.code(e.statusCode??500).send({error:e.message});}finally{client.release();} });
  app.post('/api/v1/quotes/:id/accept', { preHandler: requireAuth }, async (request: Ctx, reply) => { const client=await pool.connect(); try{await client.query('BEGIN'); const q=await client.query('SELECT * FROM quotes WHERE id=$1 AND tenant_id=$2 FOR UPDATE',[request.params.id,tenantId(request)]); if(!q.rows[0]) return reply.code(404).send({error:'Quote not found'}); await client.query("UPDATE quotes SET status='Accepted' WHERE id=$1",[request.params.id]); const inv=await client.query("INSERT INTO invoices (tenant_id,customer_id,quote_id,invoice_number,status,total,due_date) VALUES ($1,$2,$3,$4,'Sent',$5,current_date+7) RETURNING *",[tenantId(request),q.rows[0].customer_id,q.rows[0].id,`INV-${Date.now()}`,q.rows[0].total]); await client.query('INSERT INTO invoice_items (tenant_id,invoice_id,service_id,description,quantity,unit_price,discount_amount) SELECT tenant_id,$1,service_id,description,quantity,unit_price,discount_amount FROM quote_items WHERE quote_id=$2',[inv.rows[0].id,q.rows[0].id]); await client.query('COMMIT'); return inv.rows[0];}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();} });

  app.post('/api/v1/payments/request', { preHandler: requireAuth }, async (request: Ctx, reply) => { const b=request.body as any; const r=await pool.query('SELECT id,total,amount_paid FROM invoices WHERE id=$1 AND tenant_id=$2',[b.invoiceId,tenantId(request)]); if(!r.rows[0]) return reply.code(404).send({error:'Invoice not found'}); const amount=money(b.amount??Number(r.rows[0].total)-Number(r.rows[0].amount_paid)); const payment=await pool.query("INSERT INTO payments (tenant_id,invoice_id,provider,amount,status) VALUES ($1,$2,'mock',$3,'Pending') RETURNING *",[tenantId(request),b.invoiceId,amount]); return {simulated:true,payment:payment.rows[0],message:'Development payment request only; no external payment was made.'}; });
  app.post('/api/v1/payments/webhooks/mock', async (request, reply) => { const b=request.body as any; if(b?.verified!==true||!b.paymentId) return reply.code(400).send({error:'A verified development webhook is required'}); const client=await pool.connect(); try{await client.query('BEGIN'); const p=await client.query('SELECT * FROM payments WHERE id=$1 FOR UPDATE',[b.paymentId]); if(!p.rows[0]) return reply.code(404).send({error:'Payment not found'}); if(p.rows[0].status==='Verified') return {verified:true,simulated:true,idempotent:true}; await client.query("UPDATE payments SET status='Verified',verified_at=now() WHERE id=$1",[b.paymentId]); await client.query("UPDATE invoices SET amount_paid=amount_paid+$1,status=CASE WHEN amount_paid+$1>=total THEN 'Paid' ELSE 'Partially Paid' END WHERE id=$2",[p.rows[0].amount,p.rows[0].invoice_id]); await client.query('COMMIT'); return {verified:true,simulated:true};}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();} });

  app.get('/api/v1/projects', { preHandler: requireAuth }, async (request: Ctx) => pool.query('SELECT * FROM projects WHERE tenant_id=$1 ORDER BY created_at DESC',[tenantId(request)]).then(r=>r.rows));
  app.post('/api/v1/projects', { preHandler: requireAuth }, async (request: Ctx, reply) => { const b=request.body as any; const r=await pool.query("INSERT INTO projects (tenant_id,customer_id,name,status) SELECT $1,$2,$3,'Idea' WHERE EXISTS (SELECT 1 FROM customers WHERE id=$2 AND tenant_id=$1) RETURNING *",[tenantId(request),b.customerId,b.name]); if(!r.rows[0]) return reply.code(400).send({error:'Customer not found'}); return reply.code(201).send(r.rows[0]); });
  app.post('/api/v1/projects/:id/songs', { preHandler: requireAuth }, async (request: Ctx, reply) => { const b=request.body as any; const r=await pool.query('INSERT INTO songs (tenant_id,project_id,title) SELECT $1,$2,$3 WHERE EXISTS (SELECT 1 FROM projects WHERE id=$2 AND tenant_id=$1) RETURNING *',[tenantId(request),request.params.id,b.title]); if(!r.rows[0]) return reply.code(404).send({error:'Project not found'}); return reply.code(201).send(r.rows[0]); });
  app.post('/api/v1/sessions', { preHandler: requireAuth }, async (request: Ctx, reply) => { const b=request.body as any; const r=await pool.query("INSERT INTO recording_sessions (tenant_id,booking_id,project_id,song_id,status,notes) VALUES ($1,$2,$3,$4,'Scheduled',$5) RETURNING *",[tenantId(request),b.bookingId??null,b.projectId??null,b.songId??null,b.notes??null]); return reply.code(201).send(r.rows[0]); });
  app.post('/api/v1/follow-ups', { preHandler: requireAuth }, async (request: Ctx, reply) => { const b=request.body as any; const r=await pool.query('INSERT INTO follow_ups (tenant_id,customer_id,lead_id,trigger_type,scheduled_at,message) VALUES ($1,$2,$3,$4,$5,$6) RETURNING *',[tenantId(request),b.customerId??null,b.leadId??null,b.triggerType,b.scheduledAt,b.message??null]); return reply.code(201).send(r.rows[0]); });
  app.get('/api/v1/dashboard/summary', { preHandler: requireAuth }, async (request: Ctx) => { const t=tenantId(request); const [revenue,bookings,leads,projects,outstanding]=await Promise.all([pool.query("SELECT COALESCE(SUM(amount),0) AS value FROM payments WHERE tenant_id=$1 AND status='Verified' AND created_at>=date_trunc('month',now())",[t]),pool.query("SELECT count(*)::int AS value FROM bookings WHERE tenant_id=$1 AND starts_at::date=current_date AND status<>'Cancelled'",[t]),pool.query("SELECT count(*)::int AS value FROM leads WHERE tenant_id=$1 AND status NOT IN ('Lost','Converted')",[t]),pool.query("SELECT count(*)::int AS value FROM projects WHERE tenant_id=$1 AND status NOT IN ('Released','Completed')",[t]),pool.query("SELECT COALESCE(SUM(total-amount_paid),0) AS value FROM invoices WHERE tenant_id=$1 AND status NOT IN ('Paid','Cancelled')",[t])]); return {revenueThisMonth:Number(revenue.rows[0].value),bookingsToday:bookings.rows[0].value,activeLeads:leads.rows[0].value,activeProjects:projects.rows[0].value,outstandingInvoices:Number(outstanding.rows[0].value)}; });
}
